INSERT INTO candidates (id, name, email, phone, position, pos_label, city, telegram, total_exp, stack, education, verdict, status, summary, criteria, experience, questions, parsed_at, created_at, updated_at)
VALUES
    ('asanov-bakyt',
     'Асанов Бакыт Эркинович',
     'asanov.bakyt@email.com',
     '+996 700 111222',
     'java-middle',
     'Java — ведущий программист',
     'Бишкек',
     '@asanov_dev',
     '~4 г.',
     'Java 17, Spring Boot 3, PostgreSQL, Kafka, Testcontainers, Gradle, Docker',
     'КГТУ им. Раззакова, ИТ, 2021',
     'FIT',
     'NEW',
     'Backend-разработчик с 4 годами коммерческого опыта на Java. Уверенно работает со Spring Boot 3, PostgreSQL, Kafka. Пишет тесты с Testcontainers.',
     '[{"key":"java_spring","result":"OK","comment":"Java 17, Spring Boot 3 — 4 года коммерческой разработки"},{"key":"postgres","result":"OK","comment":"PostgreSQL — основная БД на всех проектах"},{"key":"kafka","result":"OK","comment":"Kafka — продюсеры, консьюмеры, партиции"},{"key":"tests","result":"OK","comment":"JUnit5, Mockito, Testcontainers"},{"key":"gradle","result":"OK","comment":"Gradle — основной инструмент сборки"},{"key":"migrations","result":"OK","comment":"Flyway — использует на текущем проекте"}]',
     '[{"period":"2023-03 — н.в.","company":"ПКБ «Финтех KG»","title":"Java Developer","duration":"~2 г."},{"period":"2021-06 — 2023-02","company":"IT-компания BARS","title":"Junior Java Developer","duration":"~1.7 г."}]',
     '["Kafka: как настраивали consumer group при нескольких репликах сервиса?","Testcontainers: насколько быстро запускаются тесты, как оптимизировали?"]',
     '2026-05-10T09:00:00Z',
     NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days');