INSERT INTO candidates (id, name, email, phone, position, pos_label, city, telegram, total_exp, stack, education, verdict, status, summary, criteria, experience, questions, created_at, updated_at)
VALUES
    ('petrov-aa',
     'Петров Алексей Андреевич',
     'petrov@email.com',
     '+996 700 111001',
     'java-middle',
     'Java — ведущий программист',
     'Бишкек',
     '@petrov_dev',
     '~4 г.',
     'Java, Spring Boot, PostgreSQL, Redis, Docker',
     'КРСУ, Информатика, 2019',
     'FIT',
     'IN_REVIEW',
     'Опытный backend-разработчик с хорошим знанием Spring.',
     '[{"key":"java_spring","result":"OK","comment":"Java 17, Spring Boot — 4 года"},{"key":"postgres","result":"OK","comment":"PostgreSQL — есть"},{"key":"kafka","result":"OK","comment":"Kafka — продакшн опыт"},{"key":"tests","result":"OK","comment":"JUnit 5, Mockito, Testcontainers"}]',
     '[{"period":"2020-03 — н.в.","company":"SoftLab","title":"Java Developer","duration":"4 г."}]',
     '["Расскажите про опыт с Kafka consumer groups","Как обеспечиваете идемпотентность?"]',
     NOW() - INTERVAL '10 days', NOW() - INTERVAL '9 days'),

    ('seitkali-mb',
     'Сейткали Мадияр Бакытбекович',
     'seitkali@email.com',
     '+996 555 222002',
     'java-middle',
     'Java — ведущий программист',
     'Алматы',
     '@seitkali_java',
     '~5 г.',
     'Java, Spring Boot, Kafka, Kubernetes, Microservices',
     'КазНУ, Программная инженерия, 2018',
     'FIT',
     'INVITED',
     'Сильный кандидат с опытом микросервисов.',
     '[{"key":"java_spring","result":"OK","comment":"Java 17+, Spring Boot 3"},{"key":"postgres","result":"OK","comment":"PostgreSQL, оптимизация запросов"},{"key":"kafka","result":"OK","comment":"Kafka — глубокий опыт"},{"key":"tests","result":"OK","comment":"TDD, Testcontainers"}]',
     '[{"period":"2019-06 — н.в.","company":"FinTech KZ","title":"Senior Java Developer","duration":"5 г."}]',
     '["Опыт с Kubernetes?","Как решаете проблемы распределённых транзакций?"]',
     NOW() - INTERVAL '15 days', NOW() - INTERVAL '5 days'),

    ('ivanova-eo',
     'Иванова Екатерина Олеговна',
     'ivanova@email.com',
     '+996 700 333003',
     'java-middle',
     'Java — ведущий программист',
     'Бишкек',
     '@ivanova_dev',
     '~3 г.',
     'Java, Spring MVC, MySQL, Hibernate',
     'КНУ, Информатика, 2021',
     'PARTIAL',
     'NEW',
     'Backend-разработчик, есть пробелы в Kafka.',
     '[{"key":"java_spring","result":"OK","comment":"Java 11, Spring MVC"},{"key":"postgres","result":"PARTIAL","comment":"MySQL преимущественно"},{"key":"kafka","result":"NO","comment":"Kafka не использовала"},{"key":"tests","result":"PARTIAL","comment":"Только unit тесты"}]',
     '[{"period":"2021-09 — н.в.","company":"WebStudio","title":"Java Developer","duration":"3 г."}]',
     '["Готовы изучить Kafka?","Опыт с PostgreSQL?"]',
     NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),

    ('abenov-dk',
     'Абенов Данияр Кайратович',
     'abenov@email.com',
     '+996 312 444004',
     'java-senior',
     'Java — главный программист',
     'Бишкек',
     '@abenov_senior',
     '~7 г.',
     'Java, Spring Boot, Kafka, Cassandra, AWS',
     'АУЦА, Компьютерные науки, 2016',
     'FIT',
     'APPROVED',
     'Отличный кандидат, соответствует всем критериям.',
     '[{"key":"java_spring","result":"OK","comment":"Java 17, Spring Boot 3 — 7 лет"},{"key":"postgres","result":"OK","comment":"PostgreSQL, партиционирование"},{"key":"kafka","result":"OK","comment":"Kafka Streams, ksqlDB"},{"key":"tests","result":"OK","comment":"Покрытие >80%"}]',
     '[{"period":"2016-08 — н.в.","company":"TechGiant","title":"Lead Java Developer","duration":"7 г."}]',
     '["Опыт архитектурных решений?"]',
     NOW() - INTERVAL '30 days', NOW() - INTERVAL '2 days'),

    ('nurlanов-as',
     'Нурланов Айбек Серикович',
     'nurlanov@email.com',
     '+996 700 555005',
     'java-junior',
     'Java — программист',
     'Ош',
     NULL,
     '~1 г.',
     'Java, Spring Boot, MySQL',
     'ОшГУ, Информатика, 2023',
     'NO_FIT',
     'REJECTED',
     'Недостаточно опыта для данной позиции.',
     '[{"key":"java_spring","result":"PARTIAL","comment":"Java 8, Spring Boot базово"},{"key":"postgres","result":"NO","comment":"Только MySQL"},{"key":"kafka","result":"NO","comment":"Kafka не использовал"},{"key":"tests","result":"NO","comment":"Тесты не писал"}]',
     '[{"period":"2023-06 — н.в.","company":"LocalIT","title":"Junior Java Developer","duration":"1 г."}]',
     '["Готовы учиться?"]',
     NOW() - INTERVAL '20 days', NOW() - INTERVAL '18 days'),

    ('bekova-zn',
     'Бекова Зарина Нурбековна',
     'bekova@email.com',
     '+7 727 666006',
     'java-middle',
     'Java — ведущий программист',
     'Алматы',
     '@bekova_java',
     '~3.5 г.',
     'Java, Spring Boot, PostgreSQL, Kafka, Docker',
     'КазГАСА, Информатика, 2020',
     'FIT',
     'IN_REVIEW',
     'Хороший кандидат, соответствует большинству требований.',
     '[{"key":"java_spring","result":"OK","comment":"Java 17, Spring Boot 3"},{"key":"postgres","result":"OK","comment":"PostgreSQL — хорошее знание"},{"key":"kafka","result":"PARTIAL","comment":"Kafka — базовый опыт"},{"key":"tests","result":"OK","comment":"JUnit 5, Mockito"}]',
     '[{"period":"2020-09 — н.в.","company":"FinSoft","title":"Java Developer","duration":"3.5 г."}]',
     '["Расскажите про опыт с Kafka","Testcontainers использовали?"]',
     NOW() - INTERVAL '7 days', NOW() - INTERVAL '6 days'),

    ('dzhaksybekov-rm',
     'Джаксыбеков Руслан Маратович',
     'dzhaksybekov@email.com',
     '+996 550 777007',
     'java-middle',
     'Java — ведущий программист',
     'Бишкек',
     '@ruslan_dev',
     '~2 г.',
     'Java, Spring Boot, MySQL, REST API',
     'КГТУ, Информатика, 2022',
     'PARTIAL',
     'NEW',
     'Есть потенциал, но недостаточно опыта с Kafka и тестированием.',
     '[{"key":"java_spring","result":"OK","comment":"Java 11/17, Spring Boot"},{"key":"postgres","result":"PARTIAL","comment":"MySQL в основном"},{"key":"kafka","result":"NO","comment":"Kafka не работал"},{"key":"tests","result":"PARTIAL","comment":"Unit тесты только"}]',
     '[{"period":"2022-03 — н.в.","company":"StartupBishkek","title":"Java Developer","duration":"2 г."}]',
     '["Планируете изучить Kafka?","Опыт с микросервисами?"]',
     NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),

    ('askarova-gk',
     'Аскарова Гульнара Кубанычбековна',
     'askarova@email.com',
     '+996 700 888008',
     'python-middle',
     'Python — ведущий программист',
     'Бишкек',
     '@askarova_py',
     '~4 г.',
     'Python, Django, FastAPI, PostgreSQL',
     'КНУ, Математика, 2020',
     'NO_FIT',
     'REJECTED',
     'Кандидат с Python-стеком, не подходит для Java-позиции.',
     '[{"key":"java_spring","result":"NO","comment":"Java не использовала"},{"key":"postgres","result":"OK","comment":"PostgreSQL — хорошее знание"},{"key":"kafka","result":"PARTIAL","comment":"Kafka — базовое знакомство"},{"key":"tests","result":"OK","comment":"pytest, хорошее покрытие"}]',
     '[{"period":"2020-01 — н.в.","company":"DataCorp","title":"Python Developer","duration":"4 г."}]',
     '["Готовы переходить на Java?"]',
     NOW() - INTERVAL '12 days', NOW() - INTERVAL '11 days'),

    ('temirov-bо',
     'Темиров Бакыт Орозбекович',
     'temirov@email.com',
     '+996 312 999009',
     'java-middle',
     'Java — ведущий программист',
     'Бишкек',
     '@temirov_java',
     '~3 г.',
     'Java, Spring Boot, PostgreSQL, Redis, RabbitMQ',
     'БГТУ, Программная инженерия, 2021',
     'PARTIAL',
     'NEW',
     'Опыт с очередями сообщений есть, но не Kafka.',
     '[{"key":"java_spring","result":"OK","comment":"Java 17, Spring Boot 3"},{"key":"postgres","result":"OK","comment":"PostgreSQL — хорошее знание"},{"key":"kafka","result":"NO","comment":"RabbitMQ, не Kafka"},{"key":"tests","result":"PARTIAL","comment":"Unit тесты, без Testcontainers"}]',
     '[{"period":"2021-07 — н.в.","company":"E-Commerce","title":"Java Developer","duration":"3 г."}]',
     '["Опыт перехода с RabbitMQ на Kafka?","Интеграционное тестирование?"]',
     NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),

    ('moldokulов-eb',
     'Молдокулов Эрлан Бекович',
     'moldokulov@email.com',
     '+996 700 100010',
     'java-senior',
     'Java — главный программист',
     'Бишкек',
     '@erlan_senior',
     '~6 г.',
     'Java, Spring Boot, Kafka, Elasticsearch, Microservices',
     'КНУ, ИВТ, 2017',
     'FIT',
     'IN_REVIEW',
     'Сильный кандидат с глубоким знанием экосистемы Java.',
     '[{"key":"java_spring","result":"OK","comment":"Java 17, Spring Boot 3 — 6 лет"},{"key":"postgres","result":"OK","comment":"PostgreSQL, сложные запросы"},{"key":"kafka","result":"OK","comment":"Kafka Streams, Connect"},{"key":"tests","result":"OK","comment":"TDD, покрытие >80%"}]',
     '[{"period":"2018-05 — н.в.","company":"TechPro","title":"Senior Java Developer","duration":"6 г."}]',
     '["Опыт с Kafka Connect?","Event sourcing паттерны?"]',
     NOW() - INTERVAL '8 days', NOW() - INTERVAL '7 days'),

    ('usenов-tk',
     'Усенов Тимур Кубанычбекович',
     'usenov@email.com',
     '+996 550 111011',
     'java-middle',
     'Java — ведущий программист',
     'Каракол',
     NULL,
     '~2.5 г.',
     'Java, Spring Boot, PostgreSQL',
     'ИГУ, Информатика, 2021',
     'PARTIAL',
     'NEW',
     'Базовый стек есть, но мало опыта с Kafka и тестированием.',
     '[{"key":"java_spring","result":"OK","comment":"Java 11, Spring Boot 2"},{"key":"postgres","result":"OK","comment":"PostgreSQL базово"},{"key":"kafka","result":"NO","comment":"Kafka не использовал"},{"key":"tests","result":"NO","comment":"Тесты не писал"}]',
     '[{"period":"2021-10 — н.в.","company":"RegionalIT","title":"Java Developer","duration":"2.5 г."}]',
     '["Планируете изучить Kafka и тестирование?"]',
     NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days'),

    ('karimов-fa',
     'Каримов Фаррух Алишерович',
     'karimov@email.com',
     '+998 90 222012',
     'java-middle',
     'Java — ведущий программист',
     'Ташкент',
     '@farrukh_java',
     '~4 г.',
     'Java, Spring Boot, Kafka, PostgreSQL, Docker, Kubernetes',
     'ТУИТ, Программная инженерия, 2019',
     'FIT',
     'NEW',
     'Хороший кандидат из Ташкента, полный стек.',
     '[{"key":"java_spring","result":"OK","comment":"Java 17, Spring Boot 3"},{"key":"postgres","result":"OK","comment":"PostgreSQL — хорошее знание"},{"key":"kafka","result":"OK","comment":"Kafka — продакшн"},{"key":"tests","result":"PARTIAL","comment":"Unit тесты, начинает с Testcontainers"}]',
     '[{"period":"2020-01 — н.в.","company":"UzTech","title":"Java Developer","duration":"4 г."}]',
     '["Готовы к переезду?","Опыт с Testcontainers?"]',
     NOW() - INTERVAL '1 days', NOW() - INTERVAL '1 days');

-- Status history for candidates that have changed status
INSERT INTO candidate_status_history (candidate_id, from_status, to_status, comment, changed_at)
VALUES
    ('petrov-aa', 'NEW', 'IN_REVIEW', 'Резюме соответствует требованиям', NOW() - INTERVAL '9 days'),
    ('seitkali-mb', 'NEW', 'IN_REVIEW', 'Отличный кандидат', NOW() - INTERVAL '14 days'),
    ('seitkali-mb', 'IN_REVIEW', 'INVITED', 'Приглашён на техническое интервью', NOW() - INTERVAL '5 days'),
    ('abenov-dk', 'NEW', 'IN_REVIEW', 'Очень сильный кандидат', NOW() - INTERVAL '28 days'),
    ('abenov-dk', 'IN_REVIEW', 'INVITED', 'Приглашён на финальное интервью', NOW() - INTERVAL '10 days'),
    ('abenov-dk', 'INVITED', 'APPROVED', 'Принят на работу', NOW() - INTERVAL '2 days'),
    ('nurlanов-as', 'NEW', 'IN_REVIEW', 'Рассмотрен', NOW() - INTERVAL '19 days'),
    ('nurlanов-as', 'IN_REVIEW', 'REJECTED', 'Недостаточно опыта', NOW() - INTERVAL '18 days'),
    ('bekova-zn', 'NEW', 'IN_REVIEW', 'Хороший кандидат', NOW() - INTERVAL '6 days'),
    ('askarova-gk', 'NEW', 'IN_REVIEW', 'Рассмотрена', NOW() - INTERVAL '11 days'),
    ('askarova-gk', 'IN_REVIEW', 'REJECTED', 'Не подходит по стеку', NOW() - INTERVAL '11 days'),
    ('moldokulов-eb', 'NEW', 'IN_REVIEW', 'Сильный кандидат', NOW() - INTERVAL '7 days');
