INSERT INTO candidates (id, name, email, phone, position, pos_label, city, telegram, total_exp, stack, education, verdict, status, summary, criteria, experience, questions, parsed_at, created_at, updated_at)
VALUES
    ('asanov-bakyt',
     'Асанов Бакыт Эркинович',
     'asanov.bakyt@email.com',
     '+996 700 111222',
     'java-middle',
     'Java — ведущий программист',
     'Бишкек',
     '@asanov_dev',
     '~4 г.',
     'Java 17, Spring Boot 3, PostgreSQL, Kafka, Testcontainers, Gradle, Docker',
     'КГТУ им. Раззакова, ИТ, 2021',
     'FIT',
     'NEW',
     'Backend-разработчик с 4 годами коммерческого опыта на Java. Уверенно работает со Spring Boot 3, PostgreSQL, Kafka. Пишет тесты с Testcontainers.',
     '[{"key":"java_spring","result":"OK","comment":"Java 17, Spring Boot 3 — 4 года коммерческой разработки"},{"key":"postgres","result":"OK","comment":"PostgreSQL — основная БД на всех проектах"},{"key":"kafka","result":"OK","comment":"Kafka — продюсеры, консьюмеры, партиции"},{"key":"tests","result":"OK","comment":"JUnit5, Mockito, Testcontainers"},{"key":"gradle","result":"OK","comment":"Gradle — основной инструмент сборки"},{"key":"migrations","result":"OK","comment":"Flyway — использует на текущем проекте"}]',
     '[{"period":"2023-03 — н.в.","company":"ПКБ «Финтех KG»","title":"Java Developer","duration":"~2 г."},{"period":"2021-06 — 2023-02","company":"IT-компания BARS","title":"Junior Java Developer","duration":"~1.7 г."}]',
     '["Kafka: как настраивали consumer group при нескольких репликах сервиса?","Testcontainers: насколько быстро запускаются тесты, как оптимизировали?"]',
     '2026-05-10T09:00:00Z',
     NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days');
INSERT INTO candidates (id, name, email, phone, position, pos_label, city, telegram, total_exp, stack, education, verdict, status, summary, criteria, experience, questions, parsed_at, created_at, updated_at)
VALUES
    ('petrov-alex',
     'Петров Алексей Сергеевич',
     'petrov.alex@email.com',
     '+996 700 222333',
     'java-middle',
     'Java — ведущий программист',
     'Бишкек',
     '@petrov_dev',
     '~3 г.',
     'Java, Spring Boot, PostgreSQL',
     'КНУ, ИТ, 2022',
     'PARTIAL',
     'IN_REVIEW',
     'Базовый стек, без Kafka.',
     '[{"key":"java_spring","result":"OK","comment":"Spring Boot"},{"key":"kafka","result":"NO","comment":"Kafka нет"}]',
     '[{"period":"2022-01 — н.в.","company":"DevCo","title":"Java Dev","duration":"3 г."}]',
     '["Планируете изучить Kafka?"]',
     '2026-05-11T10:00:00Z',
     NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),

    ('seitkali-m',
     'Сейткали Мадияр Бакытович',
     'seitkali@email.com',
     '+996 555 444555',
     'java-senior',
     'Java — главный программист',
     'Алматы',
     '@seitkali_java',
     '~6 г.',
     'Java, Spring Boot, Kafka, Kubernetes',
     'КазНУ, 2018',
     'FIT',
     'INVITED',
     'Сильный кандидат.',
     '[{"key":"java_spring","result":"OK","comment":"Java 17+"},{"key":"kafka","result":"OK","comment":"Kafka Streams"}]',
     '[{"period":"2018-06 — н.в.","company":"FinTech KZ","title":"Senior Java Dev","duration":"6 г."}]',
     '["Опыт с K8s?"]',
     '2026-05-12T10:00:00Z',
     NOW() - INTERVAL '6 days', NOW() - INTERVAL '5 days'),

    ('nurova-ai',
     'Нурова Айгерим Талантовна',
     'nurova@email.com',
     '+996 700 666777',
     'java-middle',
     'Java — ведущий программист',
     'Бишкек',
     NULL,
     '~2 г.',
     'Java, Spring Boot, MySQL',
     'КГТУ, ИТ, 2023',
     'NO_FIT',
     'REJECTED',
     'Недостаточно опыта.',
     '[{"key":"java_spring","result":"PARTIAL","comment":"Spring Boot базово"},{"key":"kafka","result":"NO","comment":"Kafka нет"}]',
     '[{"period":"2023-06 — н.в.","company":"StartupBK","title":"Junior Java Dev","duration":"2 г."}]',
     '["Готовы учиться?"]',
     '2026-05-13T10:00:00Z',
     NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),

    ('karimov-f',
     'Каримов Фаррух Алишерович',
     'karimov@email.com',
     '+998 90 888999',
     'java-middle',
     'Java — ведущий программист',
     'Ташкент',
     '@karimov_java',
     '~4 г.',
     'Java, Spring Boot, Kafka, PostgreSQL, Docker',
     'ТУИТ, 2020',
     'FIT',
     'NEW',
     'Полный стек, хороший кандидат.',
     '[{"key":"java_spring","result":"OK","comment":"Java 17"},{"key":"kafka","result":"OK","comment":"Kafka prod"}]',
     '[{"period":"2020-01 — н.в.","company":"UzTech","title":"Java Dev","duration":"4 г."}]',
     '["Готовы к переезду?"]',
     '2026-05-14T10:00:00Z',
     NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),

    ('moldokulov-e',
     'Молдокулов Эрлан Бекович',
     'moldokulov@email.com',
     '+996 700 100200',
     'java-senior',
     'Java — главный программист',
     'Бишкек',
     '@erlan_senior',
     '~7 г.',
     'Java, Spring Boot, Kafka, Elasticsearch',
     'КНУ, ИВТ, 2017',
     'FIT',
     'APPROVED',
     'Отличный кандидат, принят.',
     '[{"key":"java_spring","result":"OK","comment":"Java 17, 7 лет"},{"key":"kafka","result":"OK","comment":"Kafka Streams, Connect"}]',
     '[{"period":"2017-05 — н.в.","company":"TechPro","title":"Lead Java Dev","duration":"7 г."}]',
     '["Архитектурный опыт?"]',
     '2026-05-15T10:00:00Z',
     NOW() - INTERVAL '20 days', NOW() - INTERVAL '2 days');

INSERT INTO candidate_status_history (candidate_id, from_status, to_status, comment, changed_at)
VALUES
    ('petrov-alex', 'NEW', 'IN_REVIEW', 'Рассматривается', NOW() - INTERVAL '7 days'),
    ('seitkali-m', 'NEW', 'IN_REVIEW', 'Сильный кандидат', NOW() - INTERVAL '5 days'),
    ('seitkali-m', 'IN_REVIEW', 'INVITED', 'Приглашён на интервью', NOW() - INTERVAL '4 days'),
    ('nurova-ai', 'NEW', 'IN_REVIEW', 'Рассмотрена', NOW() - INTERVAL '4 days'),
    ('nurova-ai', 'IN_REVIEW', 'REJECTED', 'Недостаточно опыта', NOW() - INTERVAL '4 days'),
    ('moldokulov-e', 'NEW', 'IN_REVIEW', 'Отличный кандидат', NOW() - INTERVAL '18 days'),
    ('moldokulov-e', 'IN_REVIEW', 'INVITED', 'Приглашён', NOW() - INTERVAL '10 days'),
    ('moldokulov-e', 'INVITED', 'APPROVED', 'Принят на работу', NOW() - INTERVAL '2 days');